# AURAX Sprint 4 - Prometheus Configuration
# Monitoring setup for FastAPI backend and system metrics

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'aurax-monitoring'
    environment: 'development'

# Rule files for alerting (future expansion)
rule_files:
  # - "alert_rules.yml"

# Scrape configurations
scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 30s
    metrics_path: /metrics

  # AURAX FastAPI Backend
  - job_name: 'aurax-backend'
    static_configs:
      - targets: ['host.docker.internal:8000']  # For Docker on Mac/Windows
        # - targets: ['172.17.0.1:8000']        # For Docker on Linux
    scrape_interval: 10s
    metrics_path: /metrics
    scrape_timeout: 5s
    honor_labels: true
    params:
      format: ['prometheus']

  # Node Exporter for system metrics (optional)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 30s
    scrape_timeout: 10s

  # Grafana self-monitoring (optional)
  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']
    scrape_interval: 30s
    metrics_path: /metrics

# Storage configuration
storage:
  tsdb:
    path: /prometheus/data
    retention.time: 30d
    retention.size: 10GB

# Alertmanager configuration (future expansion)
# alerting:
#   alertmanagers:
#     - static_configs:
#         - targets:
#           - alertmanager:9093